# Generated by Django 2.2.17 on 2020-12-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_employee_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
