# Generated by Django 2.2.17 on 2020-12-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201223_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
