# Generated by Django 2.2.17 on 2020-12-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201223_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
